version: "1.0"
properties:
  serverversion:
    lastchecktimestamp: -62135596800
    version: 0.0.0.0
  images:
    awsregion: us-west-2
  cli:
    completionscriptpaths:
      zsh: ~/.zsh/completion/_rde
  midway:
    cookiehash: afba56b155ea78a186d660357b9e024676e15cf8
